const BM_REQUEST_TYPE = {
  GET: 0b10100001,
  SET: 0b00100001,
}

const REQUEST = {
  SET_CUR: 0x01,
  GET_CUR: 0x81,
  GET_MIN: 0x82,
  GET_MAX: 0x83,
  GET_RES: 0x84,
  GET_LEN: 0x85,
  GET_INFO: 0x86,
  GET_DEF: 0x87,
}

const PU = {
  BACKLIGHT_COMPENSATION_CONTROL: 0x01,
  BRIGHTNESS_CONTROL: 0x02,
  CONTRAST_CONTROL: 0x03,
  GAIN_CONTROL: 0x04,
  POWER_LINE_FREQUENCY_CONTROL: 0x05,
  HUE_CONTROL: 0x06,
  SATURATION_CONTROL: 0x07,
  SHARPNESS_CONTROL: 0x08,
  GAMMA_CONTROL: 0x09,
  WHITE_BALANCE_TEMPERATURE_CONTROL: 0x0A,
  WHITE_BALANCE_TEMPERATURE_AUTO_CONTROL: 0x0B,
  WHITE_BALANCE_COMPONENT_CONTROL: 0x0C,
  WHITE_BALANCE_COMPONENT_AUTO_CONTROL: 0x0D,
  DIGITAL_MULTIPLIER_CONTROL: 0x0E,
  DIGITAL_MULTIPLIER_LIMIT_CONTROL: 0x0F,
  HUE_AUTO_CONTROL: 0x10,
  ANALOG_VIDEO_STANDARD_CONTROL: 0x11,
  ANALOG_LOCK_STATUS_CONTROL: 0x12,
}

const CT = {
  SCANNING_MODE_CONTROL: 0x01,
  AE_MODE_CONTROL: 0x02,
  AE_PRIORITY_CONTROL: 0x03,
  EXPOSURE_TIME_ABSOLUTE_CONTROL: 0x04,
  EXPOSURE_TIME_RELATIVE_CONTROL: 0x05,
  FOCUS_ABSOLUTE_CONTROL: 0x06,
  FOCUS_RELATIVE_CONTROL: 0x07,
  FOCUS_AUTO_CONTROL: 0x08,
  IRIS_ABSOLUTE_CONTROL: 0x09,
  IRIS_RELATIVE_CONTROL: 0x0A,
  ZOOM_ABSOLUTE_CONTROL: 0x0B,
  ZOOM_RELATIVE_CONTROL: 0x0C,
  PANTILT_ABSOLUTE_CONTROL: 0x0D,
  PANTILT_RELATIVE_CONTROL: 0x0E,
  ROLL_ABSOLUTE_CONTROL: 0x0F,
  ROLL_RELATIVE_CONTROL: 0x10,
  PRIVACY_CONTROL: 0x11,
}

module.exports = {
  CT,
  PU,
  REQUEST,
  BM_REQUEST_TYPE
}
